//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nordic_Align_V7.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nordic_Align_V7.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla fält är obligatoriska.
        /// </summary>
        public static string Allafältärobligatoriska {
            get {
                return ResourceManager.GetString("Allafältärobligatoriska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysera användarbeteenden för att optimera upplevelsen.
        /// </summary>
        public static string Analyseraanvändarbeteenden {
            get {
                return ResourceManager.GetString("Analyseraanvändarbeteenden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra bil.
        /// </summary>
        public static string Ändrabil {
            get {
                return ResourceManager.GetString("Ändrabil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra kurir.
        /// </summary>
        public static string Ändrakurir {
            get {
                return ResourceManager.GetString("Ändrakurir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra lager.
        /// </summary>
        public static string Ändralager {
            get {
                return ResourceManager.GetString("Ändralager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra mottagare.
        /// </summary>
        public static string Ändramottagare {
            get {
                return ResourceManager.GetString("Ändramottagare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra order.
        /// </summary>
        public static string Ändraorder {
            get {
                return ResourceManager.GetString("Ändraorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange en giltig e-postadress.
        /// </summary>
        public static string Angeengiltige_postadress {
            get {
                return ResourceManager.GetString("Angeengiltige_postadress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annan information som du frivilligt tillhandahåller via våra formulär.
        /// </summary>
        public static string Annaninformation {
            get {
                return ResourceManager.GetString("Annaninformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anställnings datum.
        /// </summary>
        public static string Anställningsdatum {
            get {
                return ResourceManager.GetString("Anställningsdatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anställningsdatumet kan inte vara före 1 juli 2024..
        /// </summary>
        public static string Anställningsdatumetkanintevaraföre1juli2024 {
            get {
                return ResourceManager.GetString("Anställningsdatumetkanintevaraföre1juli2024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antal.
        /// </summary>
        public static string Antal {
            get {
                return ResourceManager.GetString("Antal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbetsdag slut.
        /// </summary>
        public static string Arbetsdagslut {
            get {
                return ResourceManager.GetString("Arbetsdagslut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbetsdag start.
        /// </summary>
        public static string Arbetsdagstart {
            get {
                return ResourceManager.GetString("Arbetsdagstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avboka.
        /// </summary>
        public static string Avboka {
            get {
                return ResourceManager.GetString("Avboka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avsändare.
        /// </summary>
        public static string Avsändare {
            get {
                return ResourceManager.GetString("Avsändare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begära information om vilka personuppgifter vi har om dig.
        /// </summary>
        public static string Begärainformationom {
            get {
                return ResourceManager.GetString("Begärainformationom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begära rättelse eller radering av dina uppgifter.
        /// </summary>
        public static string Begärarättelse_ {
            get {
                return ResourceManager.GetString("Begärarättelse ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekräfta lösenord.
        /// </summary>
        public static string Bekräftalösenord {
            get {
                return ResourceManager.GetString("Bekräftalösenord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beställnings datum.
        /// </summary>
        public static string Beställningsdatum {
            get {
                return ResourceManager.GetString("Beställningsdatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beställningsdatum från:.
        /// </summary>
        public static string Beställningsdatumfrån {
            get {
                return ResourceManager.GetString("Beställningsdatumfrån", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beställningsdatum till:.
        /// </summary>
        public static string Beställningsdatumtill {
            get {
                return ResourceManager.GetString("Beställningsdatumtill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilmärke.
        /// </summary>
        public static string Bilmärke {
            get {
                return ResourceManager.GetString("Bilmärke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekräfta lösenordet..
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Cookies.
        /// </summary>
        public static string Cookies {
            get {
                return ResourceManager.GetString("Cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CX transformations strategi.
        /// </summary>
        public static string CXtransformationsstrategi {
            get {
                return ResourceManager.GetString("CXtransformationsstrategi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data AI-lösningar.
        /// </summary>
        public static string DataAI_lösningar {
            get {
                return ResourceManager.GetString("DataAI_lösningar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datumet måste vara efter 01.01.2000.
        /// </summary>
        public static string Datumetmåstevaraefter2000 {
            get {
                return ResourceManager.GetString("Datumetmåstevaraefter2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Delning av information.
        /// </summary>
        public static string Delningavinformation {
            get {
                return ResourceManager.GetString("Delningavinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det finns inga beställningar för de valda datumen..
        /// </summary>
        public static string Detfinnsingabeställningarfördevaldadatumen {
            get {
                return ResourceManager.GetString("Detfinnsingabeställningarfördevaldadatumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detta fält är obligatoriskt.
        /// </summary>
        public static string Dettafältärobligatoriskt {
            get {
                return ResourceManager.GetString("Dettafältärobligatoriskt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Dina rättigheter.
        /// </summary>
        public static string Dinarättigheter {
            get {
                return ResourceManager.GetString("Dinarättigheter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driftsanalys.
        /// </summary>
        public static string Driftsanalys {
            get {
                return ResourceManager.GetString("Driftsanalys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drifts hantering.
        /// </summary>
        public static string Driftshantering {
            get {
                return ResourceManager.GetString("Driftshantering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har rätt att:.
        /// </summary>
        public static string Duharrätt {
            get {
                return ResourceManager.GetString("Duharrätt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste välja en mottagare.
        /// </summary>
        public static string Dumåsteväljaenmottagare {
            get {
                return ResourceManager.GetString("Dumåsteväljaenmottagare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Post.
        /// </summary>
        public static string E_Post {
            get {
                return ResourceManager.GetString("E_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-postfaktura har skickats..
        /// </summary>
        public static string E_postfakturaharskickats {
            get {
                return ResourceManager.GetString("E_postfakturaharskickats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efterfråge prognos.
        /// </summary>
        public static string Efterfrågeprognos {
            get {
                return ResourceManager.GetString("Efterfrågeprognos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efternamn.
        /// </summary>
        public static string Efternamn {
            get {
                return ResourceManager.GetString("Efternamn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ej Info.
        /// </summary>
        public static string EjInfo {
            get {
                return ResourceManager.GetString("EjInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mejlet är ogiltig.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fältet är obligatorisk.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endast positivt tal.
        /// </summary>
        public static string Endastpositivttal {
            get {
                return ResourceManager.GetString("Endastpositivttal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Performance Management (EPM).
        /// </summary>
        public static string EnterprisePerformanceManagement_EPM_ {
            get {
                return ResourceManager.GetString("EnterprisePerformanceManagement(EPM)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-postadress.
        /// </summary>
        public static string Epostadress {
            get {
                return ResourceManager.GetString("Epostadress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktura.
        /// </summary>
        public static string Faktura {
            get {
                return ResourceManager.GetString("Faktura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktura (EjMoms).
        /// </summary>
        public static string FakturaEjMoms {
            get {
                return ResourceManager.GetString("FakturaEjMoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakturan har skickats framgångsrikt!.
        /// </summary>
        public static string Fakturanharskickatsframgångsrikt {
            get {
                return ResourceManager.GetString("Fakturanharskickatsframgångsrikt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakturanummer.
        /// </summary>
        public static string Fakturanummer {
            get {
                return ResourceManager.GetString("Fakturanummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fältet måste innehålla 12 siffror.
        /// </summary>
        public static string Fältetmåsteinnehålla12siffror {
            get {
                return ResourceManager.GetString("Fältetmåsteinnehålla12siffror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fältet måste innehålla minst 3 tecken.
        /// </summary>
        public static string Fältetmåsteinnehållaminst3tecken {
            get {
                return ResourceManager.GetString("Fältetmåsteinnehållaminst3tecken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fältet måste innehålla minst 6 tecken.
        /// </summary>
        public static string Fältetmåsteinnehållaminst6tecken {
            get {
                return ResourceManager.GetString("Fältetmåsteinnehållaminst6tecken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fältet måste innehålla minst 7 och max 13 tecken.
        /// </summary>
        public static string Fältetmåsteinnehållaminst7ochmax13tecken {
            get {
                return ResourceManager.GetString("Fältetmåsteinnehållaminst7ochmax13tecken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fältet måste innehålla minst två ord.
        /// </summary>
        public static string Fältetmåsteinnehållaminsttvåord {
            get {
                return ResourceManager.GetString("Fältetmåsteinnehållaminsttvåord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fältet måste innehålla minst två tecken.
        /// </summary>
        public static string Fältetmåsteinnehållaminsttvåtecken {
            get {
                return ResourceManager.GetString("Fältetmåsteinnehållaminsttvåtecken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fältet  måste vara 5 siffror långt.
        /// </summary>
        public static string Fältetmåstevara5siffrorlångt {
            get {
                return ResourceManager.GetString("Fältetmåstevara5siffrorlångt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fältet måste vara större än 0.
        /// </summary>
        public static string Fältetmåstevarastörreän0 {
            get {
                return ResourceManager.GetString("Fältetmåstevarastörreän0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Färg.
        /// </summary>
        public static string Färg {
            get {
                return ResourceManager.GetString("Färg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel.
        /// </summary>
        public static string Fel {
            get {
                return ResourceManager.GetString("Fel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel: Det gick inte att skicka e-post..
        /// </summary>
        public static string Fel_Detgickinteattskickae_post {
            get {
                return ResourceManager.GetString("Fel_Detgickinteattskickae_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel: Ett tekniskt fel uppstod.
        /// </summary>
        public static string Fel_Ettteknisktfeluppstod {
            get {
                return ResourceManager.GetString("Fel_Ettteknisktfeluppstod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel: Fakturan kunde inte skickas.
        /// </summary>
        public static string Fel_Fakturan_kunde_inte_skickas {
            get {
                return ResourceManager.GetString("Fel_Fakturan kunde inte skickas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel vid sändning. Försök igen..
        /// </summary>
        public static string Felvidsändning_Försökigen {
            get {
                return ResourceManager.GetString("Felvidsändning_Försökigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrera.
        /// </summary>
        public static string Filtrera {
            get {
                return ResourceManager.GetString("Filtrera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange ett förnamn..
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förbättra vår webbplats och tjänster.
        /// </summary>
        public static string Förbättravårwebbplats {
            get {
                return ResourceManager.GetString("Förbättravårwebbplats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Företag.
        /// </summary>
        public static string Företag {
            get {
                return ResourceManager.GetString("Företag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förfallodatum.
        /// </summary>
        public static string Förfallodatum {
            get {
                return ResourceManager.GetString("Förfallodatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forfonsflotta.
        /// </summary>
        public static string Forfonflotta {
            get {
                return ResourceManager.GetString("Forfonflotta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förnamn.
        /// </summary>
        public static string Förnamn {
            get {
                return ResourceManager.GetString("Förnamn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framtida färdplanering.
        /// </summary>
        public static string Framtidafärdplanering {
            get {
                return ResourceManager.GetString("Framtidafärdplanering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullständigt paket.
        /// </summary>
        public static string Fullständigt_paket {
            get {
                return ResourceManager.GetString("Fullständigt paket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullständigt erbjudande paket Deluxe.
        /// </summary>
        public static string FullständigterbjudandepaketDeluxe {
            get {
                return ResourceManager.GetString("FullständigterbjudandepaketDeluxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå till startsidan.
        /// </summary>
        public static string Gåtillstartsidan {
            get {
                return ResourceManager.GetString("Gåtillstartsidan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generera och skicka.
        /// </summary>
        public static string Genereraochskicka {
            get {
                return ResourceManager.GetString("Genereraochskicka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Har du inget konto?.
        /// </summary>
        public static string Harduingetkonto {
            get {
                return ResourceManager.GetString("Harduingetkonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Har du redan ett konto?.
        /// </summary>
        public static string Harduredanettkonto {
            get {
                return ResourceManager.GetString("Harduredanettkonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hem.
        /// </summary>
        public static string Hem {
            get {
                return ResourceManager.GetString("Hem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemsida.
        /// </summary>
        public static string Hemsida {
            get {
                return ResourceManager.GetString("Hemsida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoppsan!.
        /// </summary>
        public static string Hoppsan {
            get {
                return ResourceManager.GetString("Hoppsan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Hur vi använder dina uppgifter.
        /// </summary>
        public static string Hurvianvänder {
            get {
                return ResourceManager.GetString("Hurvianvänder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inköps lösningar.
        /// </summary>
        public static string Inköpslösningar {
            get {
                return ResourceManager.GetString("Inköpslösningar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Insamling av personuppgifter.
        /// </summary>
        public static string Insamlingavpersonuppgifter {
            get {
                return ResourceManager.GetString("Insamlingavpersonuppgifter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integritetspolicy.
        /// </summary>
        public static string Integritetspolicy {
            get {
                return ResourceManager.GetString("Integritetspolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Introduktion.
        /// </summary>
        public static string Introduktion {
            get {
                return ResourceManager.GetString("Introduktion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invända mot vår behandling av dina personuppgifter.
        /// </summary>
        public static string Invändamotvår {
            get {
                return ResourceManager.GetString("Invändamotvår", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP-adress och webbläsarinformation.
        /// </summary>
        public static string IPadressoch {
            get {
                return ResourceManager.GetString("IPadressoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapacitet.
        /// </summary>
        public static string Kapacitet {
            get {
                return ResourceManager.GetString("Kapacitet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Kontakt {
            get {
                return ResourceManager.GetString("Kontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Kontakt.
        /// </summary>
        public static string Kontakt_sjö {
            get {
                return ResourceManager.GetString("Kontakt_sjö", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakta dig vid behov.
        /// </summary>
        public static string Kontaktadigvid {
            get {
                return ResourceManager.GetString("Kontaktadigvid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurir.
        /// </summary>
        public static string Kurir {
            get {
                return ResourceManager.GetString("Kurir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurirer.
        /// </summary>
        public static string Kurirer {
            get {
                return ResourceManager.GetString("Kurirer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurir tabell.
        /// </summary>
        public static string Kurirtabell {
            get {
                return ResourceManager.GetString("Kurirtabell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lager.
        /// </summary>
        public static string Lager {
            get {
                return ResourceManager.GetString("Lager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lager hantering.
        /// </summary>
        public static string Lagerhantering {
            get {
                return ResourceManager.GetString("Lagerhantering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagernamn.
        /// </summary>
        public static string Lagernamn {
            get {
                return ResourceManager.GetString("Lagernamn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lager tabell.
        /// </summary>
        public static string Lagertabell {
            get {
                return ResourceManager.GetString("Lagertabell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till en fordon.
        /// </summary>
        public static string Läggtillenfordon {
            get {
                return ResourceManager.GetString("Läggtillenfordon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till kurir.
        /// </summary>
        public static string Läggtillkurir {
            get {
                return ResourceManager.GetString("Läggtillkurir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till lager.
        /// </summary>
        public static string Läggtilllager {
            get {
                return ResourceManager.GetString("Läggtilllager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till mottagare.
        /// </summary>
        public static string Läggtillmottagare {
            get {
                return ResourceManager.GetString("Läggtillmottagare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till order.
        /// </summary>
        public static string Läggtillorder {
            get {
                return ResourceManager.GetString("Läggtillorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till pris.
        /// </summary>
        public static string Läggtillpris {
            get {
                return ResourceManager.GetString("Läggtillpris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till produkt.
        /// </summary>
        public static string Läggtillprodukt {
            get {
                return ResourceManager.GetString("Läggtillprodukt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string Land {
            get {
                return ResourceManager.GetString("Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastförmåga.
        /// </summary>
        public static string Lastförmåga {
            get {
                return ResourceManager.GetString("Lastförmåga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange ett efternamn..
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverans adress.
        /// </summary>
        public static string Leveransadress {
            get {
                return ResourceManager.GetString("Leveransadress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverans datum.
        /// </summary>
        public static string Leveransdatum {
            get {
                return ResourceManager.GetString("Leveransdatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leveransdatum måste vara senare än idag.
        /// </summary>
        public static string Leveransdatummåstevarasenareänidag {
            get {
                return ResourceManager.GetString("Leveransdatummåstevarasenareänidag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga in.
        /// </summary>
        public static string Loggain {
            get {
                return ResourceManager.GetString("Loggain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoggaIn.
        /// </summary>
        public static string LoggaIn_all {
            get {
                return ResourceManager.GetString("LoggaIn_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoggaUt.
        /// </summary>
        public static string Loggaut {
            get {
                return ResourceManager.GetString("Loggaut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistik Hantering.
        /// </summary>
        public static string Logistikhantering {
            get {
                return ResourceManager.GetString("Logistikhantering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord.
        /// </summary>
        public static string Lösenord {
            get {
                return ResourceManager.GetString("Lösenord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meddelande.
        /// </summary>
        public static string Meddelande {
            get {
                return ResourceManager.GetString("Meddelande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modell.
        /// </summary>
        public static string Modell {
            get {
                return ResourceManager.GetString("Modell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mottagare.
        /// </summary>
        public static string Mottagare {
            get {
                return ResourceManager.GetString("Mottagare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mottagare(obligatoriskt).
        /// </summary>
        public static string Mottagare_obligatoriskt {
            get {
                return ResourceManager.GetString("Mottagare_obligatoriskt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mottagaren måste innehålla minst två ord.
        /// </summary>
        public static string Mottagarenmåsteinnehållaminsttvåord {
            get {
                return ResourceManager.GetString("Mottagarenmåsteinnehållaminsttvåord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mottagare tabell.
        /// </summary>
        public static string Mottagaretabell {
            get {
                return ResourceManager.GetString("Mottagaretabell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn.
        /// </summary>
        public static string Namn {
            get {
                return ResourceManager.GetString("Namn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn och kontaktuppgifter.
        /// </summary>
        public static string Namnochkontaktuppgifter {
            get {
                return ResourceManager.GetString("Namnochkontaktuppgifter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nej.
        /// </summary>
        public static string Nej {
            get {
                return ResourceManager.GetString("Nej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omdesign av tjänster.
        /// </summary>
        public static string Omdesignavtjänster {
            get {
                return ResourceManager.GetString("Omdesignavtjänster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om du har frågor om denna integritetspolicy, vänligen kontakta oss på:.
        /// </summary>
        public static string Omduharfrågoromdenna {
            get {
                return ResourceManager.GetString("Omduharfrågoromdenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om oss.
        /// </summary>
        public static string Omoss {
            get {
                return ResourceManager.GetString("Omoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi har ett uppdrag att leverera oöverträffad expertis för att optimera våra kunders försörjningskedje operationer, vilket främjar deras tillväxt och framgång på global nivå..
        /// </summary>
        public static string OmOss_text1 {
            get {
                return ResourceManager.GetString("OmOss_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Våra affärsmål och vår strategi innebär att vi arbetar genom en väl definierad metod, vilket gör det möjligt för oss att bana väg för våra kunders framgång samtidigt som vi maximerar effekten av våra tjänster..
        /// </summary>
        public static string OmOss_text2 {
            get {
                return ResourceManager.GetString("OmOss_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Våra produkter omfattar ett utbud av konsulttjänster för optimering av försörjningskedjan, vilka används för att säkerställa att utbudets fungerar smidigt och resulterar i lägre kostnader samt en snabbare produktions- och leveranscykel..
        /// </summary>
        public static string OmOss_text3 {
            get {
                return ResourceManager.GetString("OmOss_text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation är omöjlig. Fordonen är kopplad till aktiva beställningar..
        /// </summary>
        public static string Operationäromöjlig_Fordonenärkoppladtillaktivabeställningar {
            get {
                return ResourceManager.GetString("Operationäromöjlig_Fordonenärkoppladtillaktivabeställningar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation är omöjlig. Kuriren har aktiva beställningar..
        /// </summary>
        public static string Operationäromöjlig_Kuriren {
            get {
                return ResourceManager.GetString("Operationäromöjlig_Kuriren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation är omöjlig. Lagret har aktiva beställningar..
        /// </summary>
        public static string Operationäromöjlig_Lagretharaktivabeställningar {
            get {
                return ResourceManager.GetString("Operationäromöjlig_Lagretharaktivabeställningar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation är omöjlig. Mottagaren har aktiva beställningar..
        /// </summary>
        public static string Operationäromöjlig_Mottagarenharaktivabeställningar {
            get {
                return ResourceManager.GetString("Operationäromöjlig_Mottagarenharaktivabeställningar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order tabell.
        /// </summary>
        public static string Ordertabell {
            get {
                return ResourceManager.GetString("Ordertabell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort.
        /// </summary>
        public static string Ort {
            get {
                return ResourceManager.GetString("Ort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fältet är obligatorisk.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenorden matchar inte..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnummer.
        /// </summary>
        public static string Personnummer {
            get {
                return ResourceManager.GetString("Personnummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postnummer.
        /// </summary>
        public static string Postnummer {
            get {
                return ResourceManager.GetString("Postnummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestanda utvärdering.
        /// </summary>
        public static string Prestandautvärdering {
            get {
                return ResourceManager.GetString("Prestandautvärdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pris.
        /// </summary>
        public static string Pris {
            get {
                return ResourceManager.GetString("Pris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        public static string Produkt {
            get {
                return ResourceManager.GetString("Produkt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegDatum.
        /// </summary>
        public static string RegDatum {
            get {
                return ResourceManager.GetString("RegDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrera dig.
        /// </summary>
        public static string Registreradig {
            get {
                return ResourceManager.GetString("Registreradig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrering.
        /// </summary>
        public static string Registrering {
            get {
                return ResourceManager.GetString("Registrering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrering.
        /// </summary>
        public static string Registrering_Skapa {
            get {
                return ResourceManager.GetString("Registrering_Skapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreringsdatum.
        /// </summary>
        public static string Registreringsdatum {
            get {
                return ResourceManager.GetString("Registreringsdatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreringsnummer.
        /// </summary>
        public static string Registreringsnummer {
            get {
                return ResourceManager.GetString("Registreringsnummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegNo.
        /// </summary>
        public static string RegNo {
            get {
                return ResourceManager.GetString("RegNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidan du letar efter är inte tillgänglig..
        /// </summary>
        public static string Sidanduletarefter {
            get {
                return ResourceManager.GetString("Sidanduletarefter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa faktura.
        /// </summary>
        public static string Skapafaktura {
            get {
                return ResourceManager.GetString("Skapafaktura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa faktura(Ej Moms).
        /// </summary>
        public static string SkapafakturaEj_Moms {
            get {
                return ResourceManager.GetString("SkapafakturaEj Moms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa konto.
        /// </summary>
        public static string Skapakonto {
            get {
                return ResourceManager.GetString("Skapakonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa lösenord.
        /// </summary>
        public static string Skapalösenord {
            get {
                return ResourceManager.GetString("Skapalösenord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skräddarsydda IT-lösningar.
        /// </summary>
        public static string SkräddarsyddaIT_lösningar {
            get {
                return ResourceManager.GetString("SkräddarsyddaIT_lösningar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluttiden måste vara senare än starttiden.
        /// </summary>
        public static string Sluttidenmåstevarasenareänstarttiden {
            get {
                return ResourceManager.GetString("Sluttidenmåstevarasenareänstarttiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök efter.
        /// </summary>
        public static string Sökefter {
            get {
                return ResourceManager.GetString("Sökefter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök på kurirnamn.
        /// </summary>
        public static string Sökpåkurirnamn {
            get {
                return ResourceManager.GetString("Sökpåkurirnamn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara.
        /// </summary>
        public static string Spara {
            get {
                return ResourceManager.GetString("Spara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stad.
        /// </summary>
        public static string Stad {
            get {
                return ResourceManager.GetString("Stad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard erbjudande paket.
        /// </summary>
        public static string Standarderbjudandepaket {
            get {
                return ResourceManager.GetString("Standarderbjudandepaket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategi implementering.
        /// </summary>
        public static string Strategiimplementering {
            get {
                return ResourceManager.GetString("Strategiimplementering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tack för ditt meddelande! Vi kommer att svara så snart som möjligt.
        /// </summary>
        public static string Tackfördittmeddelande {
            get {
                return ResourceManager.GetString("Tackfördittmeddelande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjänste hantering.
        /// </summary>
        public static string Tjänstehantering {
            get {
                return ResourceManager.GetString("Tjänstehantering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjänster.
        /// </summary>
        public static string Tjänster {
            get {
                return ResourceManager.GetString("Tjänster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett baspaket erbjuds tillsammans med tilläggstjänster såsom framtida färdplanering, IT-lösningar, optimering, analys och andra mervärdestjänster. Vi erbjuder dessutom följande tjänster till fast pris inom paketlösningar:.
        /// </summary>
        public static string Tjänster_text {
            get {
                return ResourceManager.GetString("Tjänster_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett baspaket erbjuds tillsammans med tilläggstjänster såsom framtida färdplanering, IT-lösningar, optimering, analys och andra mervärdestjänster. Vi erbjuder dessutom följande tjänster till fast pris inom paketlösningar:
        ///
        ///.
        /// </summary>
        public static string Tjänster_text1 {
            get {
                return ResourceManager.GetString("Tjänster_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport tabell.
        /// </summary>
        public static string Transporttabell {
            get {
                return ResourceManager.GetString("Transporttabell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utfärdandedatum.
        /// </summary>
        public static string Utfärdandedatum {
            get {
                return ResourceManager.GetString("Utfärdandedatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vad är det vi erbjuder?.
        /// </summary>
        public static string Vadärdetvierbjuder {
            get {
                return ResourceManager.GetString("Vadärdetvierbjuder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj mottagare (krävs).
        /// </summary>
        public static string Väljmottagare_krävs_ {
            get {
                return ResourceManager.GetString("Väljmottagare(krävs)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vänligen ange ett giltigt datum.
        /// </summary>
        public static string Vänligenangeettgiltigtdatum {
            get {
                return ResourceManager.GetString("Vänligenangeettgiltigtdatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vänligen ange sluttid.
        /// </summary>
        public static string Vänligenangesluttid {
            get {
                return ResourceManager.GetString("Vänligenangesluttid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vänligen ange starttid.
        /// </summary>
        public static string Vänligenangestarttid {
            get {
                return ResourceManager.GetString("Vänligenangestarttid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat nummer.
        /// </summary>
        public static string Vatnummer {
            get {
                return ResourceManager.GetString("Vatnummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi använder cookies för att förbättra din användarupplevelse. Du kan när som helst ändra dina cookie-inställningar i din webbläsare..
        /// </summary>
        public static string Vianvändercookiesför {
            get {
                return ResourceManager.GetString("Vianvändercookiesför", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi använder din information för att:.
        /// </summary>
        public static string Vianvänderdin {
            get {
                return ResourceManager.GetString("Vianvänderdin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi delar inte dina personuppgifter med tredje part, förutom om det krävs enligt lag eller för att leverera våra tjänster..
        /// </summary>
        public static string Videlarintedina {
            get {
                return ResourceManager.GetString("Videlarintedina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi kan samla in följande information:.
        /// </summary>
        public static string Vikansamlain {
            get {
                return ResourceManager.GetString("Vikansamlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vilkor (valfritt).
        /// </summary>
        public static string Vilkor_valfritt {
            get {
                return ResourceManager.GetString("Vilkor_valfritt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villkor.
        /// </summary>
        public static string Villkor {
            get {
                return ResourceManager.GetString("Villkor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi värnar om din integritet och skyddar dina personuppgifter. Denna integritetspolicy förklarar hur vi samlar in, använder och skyddar din information när du använder vår webbplats..
        /// </summary>
        public static string Vivärnaromdin {
            get {
                return ResourceManager.GetString("Vivärnaromdin", resourceCulture);
            }
        }
    }
}
